### ISSUE TITLE
We have released a typo in teh consensus.

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion-em-xmipp#384]
https://github.com/I2PC/scipion-em-xmipp/blob/master/xmipp3/protocols/protocol_ctf_consensus.py#L447

PhaseShit --> PhaseShift

**Comment by DStrelak** [comment]
Fixed in devel (https://github.com/I2PC/scipion-em-xmipp/commit/332b8ab7f88a184faf69040cfab19c4e6a4f6bd3)

**Comment by pconesa** [comment]
I think we are making 2 mistakes here.

1.- fixing hot fix in devel. If we follow gitflow, that fix should have gone to a hotfix branch and be released
2.-if we do not follow gitflow, then this fix stays in devel for xmipp developers, but scipion and xmipp users will still get the error (already reported by one of our users) until devel is released ....and we all know that devel release will not happen anytime soon.

**Comment by dmaluenda** [comment]
We could make a cherry pick of https://github.com/I2PC/scipion-em-xmipp/commit/332b8ab7f88a184faf69040cfab19c4e6a4f6bd3 in a master-based branch (hot-fixing branch).

**Comment by pconesa** [comment]
I'd also recommend to add a github action, as most of the plugins in scipion-em have to automatically release and tag any code accepted in master.

**Comment by DStrelak** [comment]
> I'd also recommend to add a github action, as most of the plugins in scipion-em have to automatically release and tag any code accepted in master.

That would be a very nice feature. However, we would still have to be careful to release only changes which are not conflicting with Xmipp binaries.
